services:
  - type: web
    name: groundwater-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/database.py
      python backend/load_stations.py
      python backend/generate_data.py
      python backend/refresh.py
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
